#!/usr/bin/env python3
"""Rasterize the pinned Lucide SVG sources into compact firmware masks."""
from __future__ import annotations

import argparse
import json
from io import BytesIO
from pathlib import Path
import sys

try:
    from PIL import Image
    import resvg_py
except ImportError as error:  # pragma: no cover - exercised by a useful CLI error
    raise SystemExit(
        "Missing icon build dependencies. Run with: "
        "uv run --with resvg-py==0.5.0 --with pillow==12.3.0 python tools/icons/build.py"
    ) from error


ROOT = Path(__file__).resolve().parents[2]
SOURCE_DIR = ROOT / "tools/icons/sources"
OUTPUT_DIR = ROOT / "firmware/main"
MASK_SIZE = 48
SUPERSAMPLE = 2


def icon_names() -> list[str]:
    provenance = json.loads((SOURCE_DIR / "PROVENANCE.json").read_text())
    names = provenance["icons"]
    if len(names) != len(set(names)) or not names:
        raise SystemExit("PROVENANCE.json must contain a non-empty unique icon list")
    missing = [name for name in names if not (SOURCE_DIR / f"{name}.svg").is_file()]
    if missing:
        raise SystemExit(f"Missing pinned SVG sources: {', '.join(missing)}")
    return names


def rasterize(name: str) -> list[int]:
    svg = (SOURCE_DIR / f"{name}.svg").read_text()
    png = resvg_py.svg_to_bytes(
        svg_string=svg,
        width=MASK_SIZE * SUPERSAMPLE,
        height=MASK_SIZE * SUPERSAMPLE,
        shape_rendering="geometric_precision",
    )
    alpha = Image.open(BytesIO(png)).convert("RGBA").getchannel("A")
    alpha = alpha.resize((MASK_SIZE, MASK_SIZE), Image.Resampling.LANCZOS)
    return [max(0, min(15, (value * 15 + 127) // 255)) for value in alpha.get_flattened_data()]


def format_mask(name: str, pixels: list[int]) -> str:
    if len(pixels) != MASK_SIZE * MASK_SIZE:
        raise ValueError(f"{name}: expected a {MASK_SIZE}x{MASK_SIZE} mask")
    packed = [(pixels[i] << 4) | pixels[i + 1] for i in range(0, len(pixels), 2)]
    lines = ["// Generated by tools/icons/build.py; do not edit."]
    lines.append(f"static const uint8_t icon_mask_{name.replace('-', '_')}[ICON_MASK_BYTES] = {{")
    for y in range(MASK_SIZE):
        row = packed[y * (MASK_SIZE // 2) : (y + 1) * (MASK_SIZE // 2)]
        lines.append("    " + ", ".join(f"0x{v:02x}" for v in row) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def format_table(names: list[str]) -> str:
    lines = [
        "// Generated by tools/icons/build.py; do not edit.",
        '#include "icons.h"',
    ]
    lines.extend(f'#include "icon_{name.replace("-", "_")}.inc"' for name in names)
    lines.extend(
        [
            "",
            "static const uint8_t *const g_icon_masks[ICON_COUNT] = {",
        ]
    )
    lines.extend(
        f"    [ICON_{name.replace('-', '_').upper()}] = icon_mask_{name.replace('-', '_')}," for name in names
    )
    lines.append("};")
    return "\n".join(lines) + "\n"


def expected_files(names: list[str]) -> dict[Path, str]:
    generated = {OUTPUT_DIR / f"icon_{name.replace('-', '_')}.inc": format_mask(name, rasterize(name)) for name in names}
    generated[OUTPUT_DIR / "icon_data.h"] = format_table(names)
    return generated


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated firmware masks are stale")
    args = parser.parse_args()
    names = icon_names()
    generated = expected_files(names)
    expected_paths = {path.name for path in generated}
    actual_paths = {path.name for path in OUTPUT_DIR.glob("icon_*.inc")}
    stale = sorted(actual_paths - expected_paths)
    if stale:
        print("Unexpected generated icon files: " + ", ".join(stale), file=sys.stderr)
        return 1
    changed = []
    for path, contents in generated.items():
        if not path.exists() or path.read_text() != contents:
            changed.append(path)
            if not args.check:
                path.write_text(contents)
    if args.check and changed:
        print("Stale generated icon data: " + ", ".join(p.name for p in changed), file=sys.stderr)
        return 1
    if args.check:
        print(f"ok: {len(names)} Lucide masks are current")
    else:
        print(f"generated {len(names)} Lucide masks ({MASK_SIZE}x{MASK_SIZE}, 4-bit alpha)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
