// Bitmap fonts for on-screen text (setup card). Glyphs are 4-bit coverage at
// the panel's 480 px resolution, generated by tools/font/gen-font.swift.
#pragma once
#include <stdint.h>

enum { FONT_STRONG = 0, FONT_TITLE, FONT_CODE, FONT_CARD, FONT_BIG, FONT_COUNT };  // CODE: A-Z 0-9; BIG: ASCII

typedef struct {
    uint16_t cp;      // Unicode code point (table is sorted)
    uint8_t w, h;     // bitmap size, px
    int8_t x, top;    // left bearing; rows above the baseline of the first row
    uint16_t adv;     // advance, 1/16 px
    uint32_t off;     // into px[]: rows of ceil(w/2) bytes, low nibble first
} font_glyph_t;

typedef struct {
    const font_glyph_t *g;
    const uint8_t *px;
    const uint16_t *kern_pair;  // glyph index pairs (first << 8 | second), sorted
    const int8_t *kern_q4;      // their kerning, 1/16 px
    uint16_t n, n_kern;
    uint8_t ascent, descent;
    uint8_t cap;                // height of the capitals, px
} font_t;

extern const font_t g_fonts[FONT_COUNT];

// How each kind of text is set: the one place for fonts, tracking and line height. Text is placed by the middle
// of its capitals (sc_label), so a label sits where its box's centre is, whatever the font.
typedef enum {
    TXT_BUBBLE,   // status bubble
    TXT_HEADING,  // title of a setup / pairing card (capitals)
    TXT_CHIP,     // detail line on a chip (capitals)
    TXT_CAPTION,  // small caption: the command, the cron countdown
    TXT_ACTION,   // menu buttons, battery
    TXT_CHOICE,   // one of a few choices in a switch
    TXT_NUMBER,   // slider level
    TXT_CODE,     // one character of the pairing code
    TXT_CARD,     // reading card
    TXT_PAGE_TITLE, // fixed English page titles, 40 px
    TXT_PAGE_BODY,  // readable settings/guide content, 32 px
    TXT_ROLES
} text_role_t;
typedef struct {
    uint8_t font;
    uint8_t line;  // baseline to baseline, px
    float track;   // extra px between letters
} text_style_t;
extern const text_style_t g_text[TXT_ROLES];

// Next code point of a UTF-8 string (advances *s; malformed bytes yield '?').
uint32_t font_utf8_next(const char **s);
// Glyph index for a code point, or the index of '?'.
int font_glyph(const font_t *f, uint32_t cp);
// Extra advance (1/16 px, usually negative) between two glyph indices.
int font_kern(const font_t *f, int first, int second);
