// Generated by tools/icons/build.py; do not edit.
#include "icons.h"
#include "icon_circle_alert.inc"
#include "icon_circle_help.inc"
#include "icon_hourglass.inc"
#include "icon_wifi_off.inc"
#include "icon_unplug.inc"
#include "icon_mic.inc"
#include "icon_key_round.inc"
#include "icon_plug.inc"
#include "icon_brain.inc"
#include "icon_check.inc"
#include "icon_volume_2.inc"
#include "icon_square.inc"
#include "icon_wrench.inc"
#include "icon_code_xml.inc"
#include "icon_globe.inc"
#include "icon_upload.inc"
#include "icon_blocks.inc"
#include "icon_fold_horizontal.inc"
#include "icon_power.inc"
#include "icon_sun.inc"
#include "icon_volume_x.inc"
#include "icon_qr_code.inc"
#include "icon_audio_lines.inc"
#include "icon_zap.inc"

static const uint8_t *const g_icon_masks[ICON_COUNT] = {
    [ICON_CIRCLE_ALERT] = icon_mask_circle_alert,
    [ICON_CIRCLE_HELP] = icon_mask_circle_help,
    [ICON_HOURGLASS] = icon_mask_hourglass,
    [ICON_WIFI_OFF] = icon_mask_wifi_off,
    [ICON_UNPLUG] = icon_mask_unplug,
    [ICON_MIC] = icon_mask_mic,
    [ICON_KEY_ROUND] = icon_mask_key_round,
    [ICON_PLUG] = icon_mask_plug,
    [ICON_BRAIN] = icon_mask_brain,
    [ICON_CHECK] = icon_mask_check,
    [ICON_VOLUME_2] = icon_mask_volume_2,
    [ICON_SQUARE] = icon_mask_square,
    [ICON_WRENCH] = icon_mask_wrench,
    [ICON_CODE_XML] = icon_mask_code_xml,
    [ICON_GLOBE] = icon_mask_globe,
    [ICON_UPLOAD] = icon_mask_upload,
    [ICON_BLOCKS] = icon_mask_blocks,
    [ICON_FOLD_HORIZONTAL] = icon_mask_fold_horizontal,
    [ICON_POWER] = icon_mask_power,
    [ICON_SUN] = icon_mask_sun,
    [ICON_VOLUME_X] = icon_mask_volume_x,
    [ICON_QR_CODE] = icon_mask_qr_code,
    [ICON_AUDIO_LINES] = icon_mask_audio_lines,
    [ICON_ZAP] = icon_mask_zap,
};
