// Renders the on-screen fonts into bounded font_data_*.inc fragments: 4-bit coverage
// glyphs at the panel's full 480 px resolution (text is drawn after the 2x
// upscale, so it stays sharp), Latin + Cyrillic.
//
//   python3 tools/font/write-font.py
//
// Typeface: PT Sans / PT Sans Caption by ParaType (SIL Open Font License 1.1).
// Pinned Google Fonts sources in tools/font/sources make rebuilds reproducible.
import CoreGraphics
import CoreText
import Foundation

let directory = URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("sources")
let files = [
    "PT_Sans-Web-Regular.ttf", "PT_Sans-Web-Bold.ttf",
    "PT_Sans-Caption-Web-Regular.ttf", "PT_Sans-Caption-Web-Bold.ttf",
]
let faces = files.flatMap { file -> [CTFontDescriptor] in
    CTFontManagerCreateFontDescriptorsFromURL(directory.appendingPathComponent(file) as CFURL) as! [CTFontDescriptor]
}
func face(_ name: String, _ px: CGFloat) -> CTFont {
    let d = faces.first { (CTFontDescriptorCopyAttribute($0, kCTFontNameAttribute) as! String) == name }!
    return CTFontCreateWithFontDescriptor(d, px, nil)
}

var text: [UInt16] = Array(0x20...0x7E)
text += Array(0x410...0x44F) + [0x401, 0x451]
text += [0xAB, 0xBB, 0x2026, 0x2013, 0x2014, 0x2011, 0x2018, 0x2019, 0x201C, 0x201D, 0xB7, 0x2116,
         0x2022, 0xB0, 0xD7, 0x2212, 0x20BD, 0x2192]  // • ° × − ₽ →
text.sort()
// Pairing codes only: capitals, digits, and '?' for anything else.
let code: [UInt16] = ([0x20, 0x3F] + Array(0x30...0x39) + Array(0x41...0x5A)).sorted()

// Big values in the settings menu: ASCII only.
let ascii: [UInt16] = Array(0x20...0x7E)

// Must match font.h (FONT_STRONG, FONT_TITLE, FONT_CODE, FONT_CARD, FONT_BIG).
let fonts: [(String, String, CGFloat, [UInt16])] = [
    ("strong", "PTSans-CaptionBold", 20, text),
    ("title", "PTSans-Bold", 26, text),
    ("code", "PTSans-Bold", 46, code),
    ("card", "PTSans-Regular", 32, text),  // text cards: readable at arm's length
    ("big", "PTSans-Bold", 40, ascii),
]

var out = """
// Generated by tools/font/gen-font.swift. Do not edit.
// PT Sans and PT Sans Caption (c) ParaType, SIL Open Font License 1.1.
#include "font.h"


"""
var names: [String] = []

// Kerning the way CoreText sets a two-letter line, less the two advances, in 1/16 px; only pairs that move by half
// a pixel or more (the pen is rounded to whole pixels, so less cannot show).
// Only letters, digits and the punctuation of running text take part (and Cyrillic where the font shows it).
func kerns(_ cp: UInt16, _ cyrillic: Bool) -> Bool {
    let plain = (0x30...0x39).contains(cp) || (0x41...0x5A).contains(cp) || (0x61...0x7A).contains(cp)
    return plain || ".,:;!?'-%/+\u{2019}".utf16.contains(cp) || (cyrillic && (0x401...0x451).contains(cp))
}

func kerning(_ f: CTFont, _ chars: [UInt16], _ cyrillic: Bool, _ glyph: (UInt16) -> CGGlyph) -> [(Int, Int)] {
    func width(_ s: [UInt16]) -> CGFloat {
        let a = NSAttributedString(string: String(utf16CodeUnits: s, count: s.count),
                                   attributes: [NSAttributedString.Key(kCTFontAttributeName as String): f])
        return CGFloat(CTLineGetTypographicBounds(CTLineCreateWithAttributedString(a), nil, nil, nil))
    }
    var advance: [CGFloat] = []
    for cp in chars {
        var g = glyph(cp), adv = CGSize.zero
        CTFontGetAdvancesForGlyphs(f, .horizontal, &g, &adv, 1)
        advance.append(adv.width)
    }
    var pairs: [(Int, Int)] = []
    for (i, a) in chars.enumerated() where kerns(a, cyrillic) {
        for (j, b) in chars.enumerated() where kerns(b, cyrillic) {
            let q = Int(((width([a, b]) - advance[i] - advance[j]) * 16).rounded())
            if abs(q) >= 8 { pairs.append((i << 8 | j, max(-128, min(127, q)))) }
        }
    }
    return pairs
}

for (tag, name, px, chars) in fonts {
    let f = face(name, px)
    var data: [UInt8] = []
    var rows: [String] = []
    for cp in chars {
        var u = cp
        var g: CGGlyph = 0
        CTFontGetGlyphsForCharacters(f, &u, &g, 1)
        var adv = CGSize.zero
        CTFontGetAdvancesForGlyphs(f, .horizontal, &g, &adv, 1)
        var r = CTFontGetBoundingRectsForGlyphs(f, .horizontal, &g, nil, 1)
        if r.isEmpty { r = .zero }
        let x0 = Int(floor(r.minX)) - 1, x1 = Int(ceil(r.maxX)) + 1
        let y0 = Int(floor(r.minY)) - 1, y1 = Int(ceil(r.maxY)) + 1
        var w = cp == 0x20 ? 0 : x1 - x0, h = cp == 0x20 ? 0 : y1 - y0
        let off = data.count
        if w > 0 && h > 0 {
            let ctx = CGContext(data: nil, width: w, height: h, bitsPerComponent: 8, bytesPerRow: w,
                                space: CGColorSpaceCreateDeviceGray(), bitmapInfo: CGImageAlphaInfo.none.rawValue)!
            ctx.setFillColor(gray: 0, alpha: 1)
            ctx.fill(CGRect(x: 0, y: 0, width: w, height: h))
            ctx.setShouldAntialias(true)
            ctx.setAllowsFontSmoothing(false)
            ctx.setShouldSubpixelPositionFonts(false)
            ctx.setFillColor(gray: 1, alpha: 1)
            var pos = CGPoint(x: CGFloat(-x0), y: CGFloat(-y0))
            CTFontDrawGlyphs(f, &g, &pos, 1, ctx)
            let p = ctx.data!.bindMemory(to: UInt8.self, capacity: w * h)
            // Trim empty rows/columns left by the padding.
            var t = 0, b = h - 1, l = 0, rr = w - 1
            func row(_ y: Int) -> Bool { (0..<w).contains { p[y * w + $0] > 8 } }
            func col(_ x: Int) -> Bool { (0..<h).contains { p[$0 * w + x] > 8 } }
            while t < b && !row(t) { t += 1 }
            while b > t && !row(b) { b -= 1 }
            while l < rr && !col(l) { l += 1 }
            while rr > l && !col(rr) { rr -= 1 }
            let nw = rr - l + 1, nh = b - t + 1
            for y in t...b {  // bitmap rows are top-down in memory
                var byte: UInt8 = 0
                for x in 0..<nw {
                    let v = UInt8((Int(p[y * w + l + x]) * 15 + 127) / 255)
                    if x % 2 == 0 { byte = v } else { data.append(byte | (v << 4)) }
                }
                if nw % 2 == 1 { data.append(byte) }
            }
            // top edge: bitmap row 0 is at y1-1 in font space; after trimming t rows
            let top = (h - t) + y0  // pixels above the baseline of the first row
            rows.append(String(format: "    {0x%04X, %d, %d, %d, %d, %d, %d},", cp, nw, nh, x0 + l, top,
                               Int((adv.width * 16).rounded()), off))
            continue
        }
        w = 0; h = 0
        rows.append(String(format: "    {0x%04X, 0, 0, 0, 0, %d, %d},", cp, Int((adv.width * 16).rounded()), off))
    }
    out += "static const uint8_t \(tag)_px[\(data.count)] = {\n"
    for i in stride(from: 0, to: data.count, by: 24) {
        out += "    " + data[i..<min(i + 24, data.count)].map { String(format: "0x%02x,", $0) }.joined(separator: " ") + "\n"
    }
    out += "};\nstatic const font_glyph_t \(tag)_glyphs[\(chars.count)] = {\n" + rows.joined(separator: "\n") + "\n};\n\n"
    let pairs = kerning(f, chars, tag == "card") { cp in
        var u = cp, g: CGGlyph = 0
        CTFontGetGlyphsForCharacters(f, &u, &g, 1)
        return g
    }
    out += "static const uint16_t \(tag)_kern_pair[\(pairs.count)] = {\n"
    for i in stride(from: 0, to: pairs.count, by: 12) {
        out += "    " + pairs[i..<min(i + 12, pairs.count)].map { String(format: "0x%04x,", $0.0) }.joined(separator: " ") + "\n"
    }
    out += "};\nstatic const int8_t \(tag)_kern_q4[\(pairs.count)] = {\n"
    for i in stride(from: 0, to: pairs.count, by: 24) {
        out += "    " + pairs[i..<min(i + 24, pairs.count)].map { "\($0.1)," }.joined(separator: " ") + "\n"
    }
    out += "};\n\n"
    let asc = Int(CTFontGetAscent(f).rounded()), desc = Int(CTFontGetDescent(f).rounded())
    let cap = Int(CTFontGetCapHeight(f).rounded())
    names.append("    {\(tag)_glyphs, \(tag)_px, \(tag)_kern_pair, \(tag)_kern_q4, \(chars.count), \(pairs.count), \(asc), \(desc), \(cap)},")
}
out += "const font_t g_fonts[FONT_COUNT] = {\n" + names.joined(separator: "\n") + "\n};\n"
print(out, terminator: "")
