#!/usr/bin/env python3
"""Generate bounded font-data fragments from the Swift rasterizer."""

from pathlib import Path
import subprocess

root = Path(__file__).resolve().parents[2]
generated = subprocess.run(
    ["swift", str(root / "tools/font/gen-font.swift")],
    check=True, capture_output=True, text=True,
).stdout.splitlines(keepends=True)
output = root / "firmware/main"
for old in output.glob("font_data_*.inc"):
    old.unlink()
parts = []
for first in range(0, len(generated), 450):
    name = f"font_data_{first // 450:03}.inc"
    (output / name).write_text("".join(generated[first:first + 450]))
    parts.append(name)
(output / "font_data.c").write_text(
    "// Generated by tools/font/write-font.py. Do not edit.\n"
    + "".join(f'#include "{name}"\n' for name in parts)
)
print(f"Generated {len(parts)} font fragments from {len(generated)} source lines")
