#!/usr/bin/env python3
"""Generate stable 3D morph targets and per-point wave coefficients for Tess."""
from pathlib import Path
import math
rows = []
for i in range(112):
    ring, j = divmod(i, 28)
    t = 2 * math.pi * j / 28
    z = [-.58, -.20, .20, .58][ring]
    k = [.72, 1, 1, .72][ring]
    x = 1.6 * math.sin(t) ** 3 * k
    y = -(13 * math.cos(t) - 5 * math.cos(2*t) - 2 * math.cos(3*t) - math.cos(4*t)) / 10 * k
    phi = i * 2.39996323
    uy = 1 - 2 * (i + .5) / 112
    rr = math.sqrt(1 - uy*uy)
    values = [x, y, z, rr*math.cos(phi), uy, rr*math.sin(phi), math.sin(uy*3), math.cos(uy*3)]
    rows.append('    {' + ', '.join(f'{v:.5f}f' for v in values) + '},')
path = Path(__file__).resolve().parent.parent / 'firmware/main/tess_points.h'
path.write_text('// Generated by tools/generate-tess-points.py: heart, direction, wave sin/cos.\n#pragma once\nstatic const float tess_targets[112][8] = {\n' + '\n'.join(rows) + '\n};\n')
